//root layout : 전역으로 공유되는 UI
import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ceunnseo",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
        {/* Navigation matching index.html style */}
        <nav className="fixed top-0 left-0 right-0 px-12 py-6 flex justify-between items-center z-10 pointer-events-none">
          <div className="pointer-events-auto">
            <Link
              href="/"
              className="text-white font-medium text-base hover:text-lavender-400 cursor-pointer transition-colors no-underline"
            >
              CEUNNSEO
            </Link>
          </div>
          <div>
            <Link
              href="/articles"
              className="text-white text-sm font-light tracking-wide pointer-events-auto hover:text-lavender-400 cursor-pointer transition-colors no-underline"
            >
              Articles
            </Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
