//root layout : 전역으로 공유되는 UI
import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border-b">
          <nav className="mx-auto max-w-4xl px-4 py-4">
            <ul className="flex gap-6">
              <li>
                <Link href="/" className="hover:opacity-70 transition-opacity">
                  HOME
                </Link>
              </li>
              <li>
                <Link
                  href="/articles"
                  className="hover:opacity-70 transition-opacity"
                >
                  아티클
                </Link>
              </li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
